export const DEFAULT_ACTION_PROBABILITY = 0.05;
export const DEFAULT_FACE_PROBABILITY = 0.05;
export const DEFAULT_STUTTER_PROBABILITY = 0.1;

export const OWOIFY_MAP = {
  l: 'w',
  r: 'w',
  L: 'W',
  R: 'W',
  you: 'uu',
  You: 'Uu',
  oo: 'uwu',
  e: 'we',
  na: 'nya',
  ne: 'nye',
  ni: 'nyi',
  no: 'nyo',
  nu: 'nyu',
};

export const ACTION_LIST = ['*blushes*'];

export const FACE_LIST = ['owo', 'OwO'];

export const DEFAULT_LOREM: string[] = [
  'lorem',
  'ipsum',
  'dolor',
  'sit',
  'amet',
  'consectetur',
  'adipiscing',
  'elit',
  'sed',
  'do',
  'eiusmod',
  'tempor',
  'incididunt',
  'ut',
  'labore',
  'et',
  'dolore',
  'magna',
  'aliqua',
  'Ut',
  'enim',
  'ad',
  'minim',
  'veniam',
  'quis',
  'nostrud',
  'exercitation',
  'ullamco',
  'laboris',
  'nisi',
  'ut',
  'aliquip',
  'ex',
  'ea',
  'commodo',
  'consequat',
  'duis',
  'aute',
  'irure',
  'dolor',
  'reprehenderit',
  'in',
  'voluptate',
  'velit',
  'esse',
  'cillum',
  'dolore',
  'eu',
  'fugiat',
  'nulla',
  'pariatur',
  'excepteur',
  'sint',
  'occaecat',
  'cupidatat',
  'non',
  'proident',
  'sunt',
  'in',
  'culpa',
  'qui',
  'officia',
  'deserunt',
  'ollit',
  'anim',
  'id',
  'est',
  'laborum',
];

export const LOREM_FIRST =
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.';
